### ISSUE TITLE
Incompatibility with BCLib (library mod for BetterNether & others)

### ISSUE THREAD

**Issue by floral-qua-floral** [RedstoneParadox/Better-Enchantment-Boosting#1]
[BCLib](https://www.curseforge.com/minecraft/mc-mods/bclib) is a library mod required by BetterNether, BetterEnd, and EdenRing. When it is installed alongside Better Enchantment Boosting, the game fails to launch.
* Minecraft 1.18.1
* Fabric 0.12.12
* Fabric API 0.46.1
* BCLib 1.2.5
* Better Enchantment Boosting 1.0.0

The game window never opens, and no crash report is generated. The launcher opens a popup reading: `An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience. Exit Code: 0`.

Log file: [latest.log](https://github.com/paulevsGitch/BCLib/files/7966580/latest.log)

I've also reported this issue on the BCLib repo as [issue #82](https://github.com/paulevsGitch/BCLib/issues/82).

**Comment by RedstoneParadox** [comment]
This is because I had to rip out Mojang's code for bookshelf searching and replace it with my own as their original search algorithm would tank performance for larger areas. BCLib needs to fix this on their end by not loading their mixin when mine is present and then registering their bookshelves with Better Enchantment Boosting.

**Comment by RedstoneParadox** [comment]
I've looked into it and it should be possible to fix it on my end.

**Comment by RedstoneParadox** [comment]
This is fixed in the latest release.
